### ISSUE TITLE
[PHP and 3.0.1] All # characters are converted

### ISSUE THREAD

**Issue by koreus** [Ranks/emojione#486]
Hi,

I don't know if it's a feature or a bug but it's very annoying. All # characters are converted in image.
It was not the case in version 2.2.7

The problem may come from the variable public $unicodeRegexp in Client.php

Code to reproduce

`$client = new Client(new Ruleset());
echo $client->unicodeToImage('#');`

**Comment by caseyahenson** [comment]
Great catch. We'll get this fixed and push out a patch soon.

**Comment by caseyahenson** [comment]
@koreus this issue is resolved in the 3.0.2 release.

**Comment by ellisonpatterson** [comment]
This is still happening, like for a snippit like:
```[COLOR="#fff"]😛[/COLOR]```
It's matching the #.
